defmodule DevelopGamex.Draw do
  def fill_rect(x, y, w, h), do: [:fillRect, x, y, w, h]
  def fill_style(style), do: [:fillStyle, style]
  def stroke_style(style), do: [:strokeStyle, style]
  def begin_path(), do: [:beginPath]
  def stroke(), do: [:stroke]
  def arc(x, y, radius, start_angle, end_angle), do: [:arc, x, y, radius, start_angle, end_angle]
  def move_to(x, y), do: [:moveTo, x, y]
  def line_to(x, y), do: [:lineTo, x, y]
  def draw_image(id, x, y), do: [:drawImage, id, x, y]
  def font(font), do: [:font, font]
  def fill_text(text, x, y), do: [:fillText, text, x, y]
  def play(id), do: [:play, id]
  def oscillator(type, frequency, sec), do: [:oscillator, type, frequency, sec]
end
